server:
  port: 5050
  servlet:
    context-path: /racinghub-api

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

hibernate:
  ejb:
    interceptor:
      allow_cdi_injection: true